Hassan/issue#8
mmoizhussain/riscv-sbi-basic pull request #15
Opened 2022-03-26 10:26 UTC by hassanraza164

# Pull Request Template

## Prequisites

- [X] Did you run lint -cf `filename` on your changes, if you are commiting a .c file?
- [ ] Did you run lint -sf `filename` on your changes, if you are commiting a .sh file?
- [X] Does your code compile properly using `make`?
- [X] Did you related issue number in the description?

## Description

#8 has been resolved

## Technical Debt

<Write about any missing things that you are going to do in the future related to this PR>

2022-03-28 12:01 UTC, mmoizhussain requested changes

2022-03-28 12:01 UTC, mmhus commented on code/include/env/mtvec32.h
> +#define MTVEC32_MODE_MASK 0x00000003ull
delete file, this isn't what I meant

2022-03-28 12:01 UTC, mmhus commented on code/include/env/medeleg.h
> +#ifndef RISCV_MEDELEG_H
delete file, this isn't what I meant

2022-03-28 12:01 UTC, mmhus commented on code/include/env/medeleg32.h
> +#ifndef RISCV_MEDELEG32_H
delete file, this isn't what I meant

2022-03-28 12:01 UTC, mmhus commented on code/include/env/medeleg64.h
> +#ifndef RISCV_MEDELEG64_H
delete file, this isn't what I meant

2022-03-28 12:01 UTC, mmhus commented on code/include/env/medeleg_32.h
> +#ifndef RISCV_MEDELEG_H
delete file, this isn't what I meant

2022-03-28 12:01 UTC, mmhus commented on code/include/env/mideleg.h
> +#ifndef RISCV_MIDELEG_H
delete file, this isn't what I meant

2022-03-28 12:01 UTC, mmhus commented on code/include/env/mideleg32.h
> +#ifndef RISCV_MIDELEG32_H
delete file, this isn't what I meant

2022-03-28 12:01 UTC, mmhus commented on code/include/env/mideleg64.h
> +#ifndef RISCV_MIDELEG64_H
delete file, this isn't what I meant

2022-03-28 12:01 UTC, mmhus commented on code/include/env/mideleg_32.h
> +#ifndef RISCV_MIDELEG_H
delete file, this isn't what I meant

2022-03-28 12:01 UTC, mmhus commented on code/include/env/mtvec.h
> +#ifndef RISCV_MTVEC_H
Please also add defines for MTVEC  mode field types, e.g. direct and vectored

2022-03-28 12:01 UTC, mmhus commented on code/include/env/mtvec64.h
> +#ifndef RISCV_MTVEC64_H
delete file, this isn't what I meant

2022-03-28 12:01 UTC, mmoizhussain commented on code/include/env/mtvec_32.h
> +#ifndef RISCV_MTVEC_H
delete file, this isn't what I meant

2022-03-28 12:01 UTC, mmoizhussain commented on code/include/env/stvec.h
> +#ifndef RISCV_STVEC_H
delete file, this isn't what I meant

2022-03-28 12:01 UTC, mmoizhussain commented on code/include/env/stvec32.h
> +#ifndef RISCV_STVEC32_H
delete file, this isn't what I meant

2022-03-28 12:01 UTC, mmoizhussain commented on code/include/env/stvec64.h
> +#ifndef RISCV_STVEC64_H
delete file, this isn't what I meant

2022-03-28 12:01 UTC, mmoizhussain commented on code/include/env/stvec_32.h
> +#ifndef RISCV_STVEC_H
delete file, this isn't what I meant

2022-03-28 12:01 UTC, mmoizhussain commented on code/include/env/medeleg.h
> +#ifndef RISCV_MEDELEG_H
I asked you take a look at mcause. It seems you haven't understood the purpose of this register. We will leave it for now. Try and understand the purpose of these registers, in addition also look at mcause and see what it does first.

2022-04-03 06:25 UTC, hassanraza164 commented on code/include/env/mtvec.h
> +#ifndef RISCV_MTVEC_H
Values for direct and vectored has been added

2022-04-03 06:26 UTC, hassanraza164 commented on code/include/env/medeleg.h
> +#ifndef RISCV_MEDELEG_H
i have modified the file again

2022-04-03 06:26 UTC, hassanraza164 commented on code/include/env/mideleg.h
> +#ifndef RISCV_MIDELEG_H
File has been changed

2022-04-03 06:27 UTC, hassanraza164 commented on code/include/env/stvec.h
> +#ifndef RISCV_STVEC_H
File has been modified

2022-04-03 06:49 UTC, mmoizhussain approved these changes

2022-04-03 06:49 UTC, merged