issue#09
mmoizhussain/riscv-sbi-basic pull request #32
Opened 2022-04-06 19:05 UTC by 1danish159

# Pull Request Template

## Prequisites

- [x] Did you run lint -cf `filename` on your changes, if you are commiting a .c file?
- [x] Did you run lint -sf `filename` on your changes, if you are commiting a .sh file?
- [x] Does your code compile properly using `make`?
- [x] Did you related issue number in the description?

## Description

Values added in mcause.h

## Technical Debt

No

2022-04-08 10:19 UTC, mmoizhussain requested changes

2022-04-08 10:19 UTC, mmoizhussain commented on code/include/env/mcause.h
> +#define MCAUSE_I_Supervisor_software_interrupt 0x00000001ull
change everyone to capitals.

2022-04-08 10:19 UTC, mmoizhussain commented on code/include/env/mcause.h
> +#define MCAUSE_I_Virtual_supervisor_software_interrupt 0x00000002ull
Align all values

2022-04-08 10:19 UTC, mmoizhussain commented on code/include/env/mcause.h
> +#define MCAUSE_E_Store/AMO_address_misaligned 0x00000020ull
never use `/` or `\` in identifiers, replace `\`with `_`, everywhere.

2022-04-08 10:19 UTC, mmoizhussain commented on code/include/env/mcause.h
> +#define MCAUSE_E_Environment_call_from_U-mode_or_VU-mode 0x00000080ull
only underscores are legal identifiers, replace `-` with `_` everywhere.

2022-04-08 10:19 UTC, mmoizhussain commented on code/include/env/mcause.h
>  #define MCAUSE_INTERRUPT_SHIFT 31
Add a description here, using comments to explain MCAUSE is a register of fixed length (32 bits).

2022-04-08 13:06 UTC, 1danish159 reviewed
Changes made

2022-04-09 05:47 UTC, mmoizhussain requested changes

2022-04-09 05:47 UTC, mmoizhussain commented on code/include/env/mcause.h
> +#define MCAUSE_I_MACHINE_TIMER_INTERRUPT                    0x000000400ull
Check the extra zero in this line and fix it.

2022-04-09 06:18 UTC, 1danish159 commented
Updated

2022-04-09 06:18 UTC, closed without merging